'use client';

import React, { useState, useEffect } from 'react';
import { Award, Clock, AlertCircle, CheckCircle, XCircle, ChevronLeft, ChevronRight, Flag, LayoutGrid, Play } from 'lucide-react';

export default function FullPCEPExam() {
  // Exam State: 'intro', 'test', 'review', 'result'
  const [examStatus, setExamStatus] = useState('intro');
  const [currentQuestion, setCurrentQuestion] = useState(0);
  const [answers, setAnswers] = useState({});
  const [markedForReview, setMarkedForReview] = useState(new Set());
  const [timeRemaining, setTimeRemaining] = useState(40 * 60); // 40 minutes exactly
  
  // 30 Questions - Weighted by Syllabus
  // S1: Fundamentals (18%) -> ~5 Qs
  // S2: Control Flow (29%) -> ~9 Qs
  // S3: Data Collections (25%) -> ~7 Qs
  // S4: Functions (28%) -> ~9 Qs
  const questions = [
    // --- SECTION 1: FUNDAMENTALS (5 Questions) ---
    { id: 1, text: "Which of the following variable names is illegal in Python?", opts: ["my_var", "Var2", "2ndVar", "_var"], correct: 2, cat: "Fundamentals" },
    { id: 2, text: "What is the output of the following snippet?\nprint(1, 2, 3, sep='-')", opts: ["1 2 3", "1-2-3", "1,2,3", "123"], correct: 1, cat: "Fundamentals" },
    { id: 3, text: "What is the result of the following operation?\nval = 3 // 2", opts: ["1.5", "1", "2", "3"], correct: 1, cat: "Fundamentals" },
    { id: 4, text: "Which operator is used for exponentiation (power)?", opts: ["^", "**", "exp()", "pow"], correct: 1, cat: "Fundamentals" },
    { id: 5, text: "What is the decimal value of the binary number 1011?", opts: ["10", "11", "9", "12"], correct: 1, cat: "Fundamentals" },

    // --- SECTION 2: CONTROL FLOW (9 Questions) ---
    { id: 6, text: "How many asterisks (*) will the following code print?\ni = 0\nwhile i < 3:\n    print('*')\n    i += 2", opts: ["0", "1", "2", "3"], correct: 2, cat: "Control Flow" },
    { id: 7, text: "What is the output of this code?\nx = 1\ny = 0\nz = ((x == y) and (x == y)) or not(x == y)\nprint(not z)", opts: ["True", "False", "0", "1"], correct: 1, cat: "Control Flow" },
    { id: 8, text: "Which keyword immediately stops the execution of a loop?", opts: ["stop", "continue", "break", "exit"], correct: 2, cat: "Control Flow" },
    { id: 9, text: "What is the output?\nfor i in range(1, 4, 2):\n    print(i, end='')", opts: ["1234", "123", "13", "12"], correct: 2, cat: "Control Flow" },
    { id: 10, text: "In a 'if-elif-else' block, when is the 'else' block executed?", opts: ["Always", "When the 'if' condition is True", "When none of the preceding conditions are True", "When the 'elif' condition is True"], correct: 2, cat: "Control Flow" },
    { id: 11, text: "What sequence is generated by range(3)?", opts: ["1, 2, 3", "0, 1, 2", "0, 1, 2, 3", "1, 2"], correct: 1, cat: "Control Flow" },
    { id: 12, text: "What will print?\nx = 0\nif x:\n    print('A')\nelse:\n    print('B')", opts: ["A", "B", "Error", "Nothing"], correct: 1, cat: "Control Flow" },
    { id: 13, text: "Which bitwise operator performs a logical XOR?", opts: ["|", "&", "^", "~"], correct: 2, cat: "Control Flow" },
    { id: 14, text: "Analyze the code:\na = 1\nb = 0\nc = a & b\nd = a | b\ne = a ^ b\nprint(c + d + e)", opts: ["1", "2", "3", "0"], correct: 1, cat: "Control Flow" },

    // --- SECTION 3: DATA COLLECTIONS (8 Questions) ---
    { id: 15, text: "Lists in Python are:", opts: ["Immutable", "Mutable", "Constant", "Hashable"], correct: 1, cat: "Data Collections" },
    { id: 16, text: "What is the output?\nmy_list = [1, 2, 3]\nmy_list[0] = 4\nprint(my_list)", opts: ["[1, 2, 3]", "[4, 2, 3]", "[4, 1, 2, 3]", "Error"], correct: 1, cat: "Data Collections" },
    { id: 17, text: "What is the result of this slice?\ns = 'Python'\nprint(s[1:4])", opts: ["Pyt", "yth", "ytho", "th"], correct: 1, cat: "Data Collections" },
    { id: 18, text: "How do you add 'Z' to the end of a list named 'L'?", opts: ["L.add('Z')", "L.append('Z')", "L.insert('Z')", "L[len(L)] = 'Z'"], correct: 1, cat: "Data Collections" },
    { id: 19, text: "What is the output?\nt = (1, 2, 3)\nt[1] = t[1] + t[0]", opts: ["(1, 3, 3)", "(1, 2, 3)", "TypeError", "None"], correct: 2, cat: "Data Collections" },
    { id: 20, text: "Given d = {'a': 1, 'b': 2}, what is the result of 'b' in d?", opts: ["True", "False", "2", "Error"], correct: 0, cat: "Data Collections" },
    { id: 21, text: "What is the output?\nl1 = [1, 2]\nl2 = l1\nl1[0] = 3\nprint(l2)", opts: ["[1, 2]", "[3, 2]", "[1, 3]", "Error"], correct: 1, cat: "Data Collections" },
    { id: 22, text: "What does the following code print?\nprint('a' * 3)", opts: ["a3", "aaa", "a a a", "Error"], correct: 1, cat: "Data Collections" },

    // --- SECTION 4: FUNCTIONS & EXCEPTIONS (8 Questions) ---
    { id: 23, text: "What is the default return value of a function that has no return statement?", opts: ["0", "False", "None", "Null"], correct: 2, cat: "Functions & Exceptions" },
    { id: 24, text: "Which keyword allows you to modify a global variable inside a function?", opts: ["static", "global", "nonlocal", "extern"], correct: 1, cat: "Functions & Exceptions" },
    { id: 25, text: "What is the output?\ndef fun(a=1, b=2):\n    return a + b\nprint(fun(b=3))", opts: ["3", "4", "5", "Error"], correct: 1, cat: "Functions & Exceptions" },
    { id: 26, text: "Which block is executed if an exception is NOT raised in a try-except block?", opts: ["catch", "finally", "else", "done"], correct: 2, cat: "Functions & Exceptions" },
    { id: 27, text: "What output is produced?\ndef f(x):\n    if x == 0:\n        return 0\n    return x + f(x - 1)\nprint(f(3))", opts: ["3", "6", "0", "RuntimeError"], correct: 1, cat: "Functions & Exceptions" },
    { id: 28, text: "Which exception is raised when you try to access a key that does not exist in a dictionary?", opts: ["ValueError", "IndexError", "KeyError", "LookupError"], correct: 2, cat: "Functions & Exceptions" },
    { id: 29, text: "What output is expected?\ntry:\n    print(1/0)\nexcept:\n    print('A')\nfinally:\n    print('B')", opts: ["A", "B", "A B", "RuntimeError"], correct: 2, cat: "Functions & Exceptions" },
    { id: 30, text: "What happens if you defined two parameters with the same name in a function definition?", opts: ["SyntaxError", "RuntimeError", "The first one is used", "The second one is used"], correct: 0, cat: "Functions & Exceptions" }
  ];

  // Timer Logic
  useEffect(() => {
    if (examStatus !== 'test' && examStatus !== 'review') return;
    if (timeRemaining <= 0) {
      finishExam();
      return;
    }
    const timer = setInterval(() => setTimeRemaining(t => t - 1), 1000);
    return () => clearInterval(timer);
  }, [timeRemaining, examStatus]);

  const formatTime = (seconds) => {
    const m = Math.floor(seconds / 60);
    const s = seconds % 60;
    return `${m}:${s.toString().padStart(2, '0')}`;
  };

  const handleAnswer = (idx) => {
    setAnswers(prev => ({ ...prev, [currentQuestion]: idx }));
  };

  const toggleReview = () => {
    const newSet = new Set(markedForReview);
    if (newSet.has(currentQuestion)) newSet.delete(currentQuestion);
    else newSet.add(currentQuestion);
    setMarkedForReview(newSet);
  };

  const calculateResults = () => {
    let correct = 0;
    const sectionScores = {};
    
    questions.forEach((q, idx) => {
      const isCorrect = answers[idx] === q.correct;
      if (isCorrect) correct++;
      
      if (!sectionScores[q.cat]) sectionScores[q.cat] = { total: 0, correct: 0 };
      sectionScores[q.cat].total++;
      if (isCorrect) sectionScores[q.cat].correct++;
    });

    const score = Math.round((correct / questions.length) * 1000); // Scaled to 1000 like real exam
    return { score, correct, sectionScores, passed: score >= 700 };
  };

  const finishExam = () => {
    setExamStatus('result');
  };

  // --- RENDERING SUB-COMPONENTS ---

  if (examStatus === 'intro') {
    return (
      <div className="max-w-3xl mx-auto p-8 bg-white shadow-lg rounded-xl mt-10">
        <div className="text-center mb-8">
          <div className="bg-blue-100 w-20 h-20 rounded-full flex items-center justify-center mx-auto mb-4">
            <Award className="w-10 h-10 text-blue-600" />
          </div>
          <h1 className="text-3xl font-bold text-gray-900">PCEP-30-02 Practice Exam</h1>
          <p className="text-gray-600 mt-2">Certified Entry-Level Python Programmer</p>
        </div>

        <div className="grid grid-cols-2 gap-4 mb-8">
          <div className="bg-gray-50 p-4 rounded-lg border border-gray-200">
            <h3 className="font-semibold text-gray-700">Exam Format</h3>
            <ul className="text-sm text-gray-600 mt-2 space-y-1">
              <li>• 30 Questions</li>
              <li>• 40 Minutes</li>
              <li>• Multiple Choice</li>
            </ul>
          </div>
          <div className="bg-gray-50 p-4 rounded-lg border border-gray-200">
            <h3 className="font-semibold text-gray-700">Passing Criteria</h3>
            <ul className="text-sm text-gray-600 mt-2 space-y-1">
              <li>• 70% to Pass</li>
              <li>• 700 / 1000 Points</li>
              <li>• No negative marking</li>
            </ul>
          </div>
        </div>

        <button 
          onClick={() => setExamStatus('test')}
          className="w-full bg-blue-600 text-white py-4 rounded-lg font-bold text-lg hover:bg-blue-700 transition flex items-center justify-center gap-2"
        >
          <Play className="w-5 h-5" /> Start Exam
        </button>
      </div>
    );
  }

  if (examStatus === 'result') {
    const { score, correct, sectionScores, passed } = calculateResults();
    
    return (
      <div className="max-w-4xl mx-auto p-6">
        <div className={`rounded-xl border-t-8 shadow-lg bg-white p-8 mb-6 ${passed ? 'border-green-500' : 'border-red-500'}`}>
          <div className="flex flex-col items-center text-center">
            {passed ? <CheckCircle className="w-20 h-20 text-green-500 mb-4" /> : <XCircle className="w-20 h-20 text-red-500 mb-4" />}
            <h2 className="text-3xl font-bold text-gray-900 mb-2">{passed ? 'Exam Passed' : 'Exam Failed'}</h2>
            <div className="text-5xl font-black mb-4 text-gray-800">{score}<span className="text-2xl text-gray-400 font-normal">/1000</span></div>
            <p className="text-gray-600">You answered {correct} out of 30 questions correctly.</p>
          </div>
        </div>

        <div className="grid md:grid-cols-2 gap-6">
          <div className="bg-white p-6 rounded-lg shadow">
            <h3 className="font-bold text-lg mb-4 text-gray-800">Domain Performance</h3>
            <div className="space-y-4">
              {Object.entries(sectionScores).map(([cat, stats]) => {
                const pct = Math.round((stats.correct / stats.total) * 100);
                return (
                  <div key={cat}>
                    <div className="flex justify-between text-sm mb-1">
                      <span className="font-medium text-gray-700">{cat}</span>
                      <span className="text-gray-500">{pct}%</span>
                    </div>
                    <div className="w-full bg-gray-200 rounded-full h-2.5">
                      <div className={`h-2.5 rounded-full ${pct >= 70 ? 'bg-green-500' : 'bg-orange-500'}`} style={{width: `${pct}%`}}></div>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
          
          <div className="bg-blue-50 p-6 rounded-lg border border-blue-100">
            <h3 className="font-bold text-lg mb-4 text-blue-900">Next Steps</h3>
            <p className="text-sm text-blue-800 mb-4">
              {passed 
                ? "Congratulations! You are ready for the real PCEP exam. Consider booking your slot on OpenEDG." 
                : "Don't worry. Review the sections where you scored below 70% and try again."}
            </p>
            <button onClick={() => window.location.reload()} className="w-full py-2 bg-white text-blue-600 font-semibold rounded border border-blue-200 hover:bg-blue-50">
              Retake Practice Exam
            </button>
          </div>
        </div>
      </div>
    );
  }

  if (examStatus === 'review') {
    return (
      <div className="max-w-4xl mx-auto p-6 bg-white min-h-screen">
        <div className="flex justify-between items-center mb-6 border-b pb-4">
          <h2 className="text-2xl font-bold text-gray-800">Review Your Answers</h2>
          <div className="flex gap-4 text-sm">
             <div className="flex items-center gap-1"><div className="w-3 h-3 bg-green-100 border border-green-500 rounded"></div> Answered</div>
             <div className="flex items-center gap-1"><div className="w-3 h-3 bg-yellow-100 border border-yellow-500 rounded"></div> Marked</div>
             <div className="flex items-center gap-1"><div className="w-3 h-3 bg-gray-100 border border-gray-300 rounded"></div> Unanswered</div>
          </div>
        </div>

        <div className="grid grid-cols-5 md:grid-cols-10 gap-3 mb-8">
          {questions.map((q, idx) => {
            const isAnswered = answers[idx] !== undefined;
            const isMarked = markedForReview.has(idx);
            return (
              <button
                key={idx}
                onClick={() => { setCurrentQuestion(idx); setExamStatus('test'); }}
                className={`p-2 rounded border text-sm font-medium relative ${
                  isMarked ? 'bg-yellow-50 border-yellow-400 text-yellow-800' :
                  isAnswered ? 'bg-green-50 border-green-400 text-green-800' :
                  'bg-gray-50 border-gray-200 text-gray-500'
                }`}
              >
                {idx + 1}
                {isMarked && <Flag className="w-3 h-3 absolute top-0.5 right-0.5 fill-yellow-500 text-yellow-500" />}
              </button>
            );
          })}
        </div>

        <div className="flex justify-between mt-8">
           <button 
             onClick={() => setExamStatus('test')}
             className="px-6 py-2 border border-gray-300 rounded text-gray-600 hover:bg-gray-50"
           >
             ← Back to Questions
           </button>
           <button 
             onClick={finishExam}
             className="px-6 py-2 bg-green-600 text-white rounded font-bold hover:bg-green-700"
           >
             Submit Exam Now
           </button>
        </div>
      </div>
    );
  }

  // --- MAIN TEST SCREEN ---
  const q = questions[currentQuestion];
  
  return (
    <div className="min-h-screen bg-gray-100 p-4 md:p-8 font-sans">
      <div className="max-w-4xl mx-auto bg-white shadow-xl rounded-xl overflow-hidden min-h-[600px] flex flex-col">
        {/* Header */}
        <div className="bg-slate-800 text-white p-4 flex justify-between items-center">
           <div className="font-bold text-lg">PCEP-30-02 Simulator</div>
           <div className="flex items-center gap-6">
             <div className="flex items-center gap-2 text-yellow-400">
               <Clock className="w-5 h-5" />
               <span className="font-mono text-xl">{formatTime(timeRemaining)}</span>
             </div>
             <button 
               onClick={() => setExamStatus('review')} 
               className="bg-slate-700 hover:bg-slate-600 px-3 py-1 rounded text-sm flex items-center gap-2"
             >
               <LayoutGrid className="w-4 h-4" /> Review All
             </button>
           </div>
        </div>

        {/* Progress Bar */}
        <div className="w-full bg-gray-200 h-1.5">
          <div className="bg-blue-600 h-1.5 transition-all duration-300" style={{width: `${((currentQuestion + 1) / 30) * 100}%`}}></div>
        </div>

        {/* Question Area */}
        <div className="flex-1 p-8 overflow-y-auto">
          <div className="flex justify-between items-start mb-6">
            <span className="text-sm font-bold text-slate-500 uppercase tracking-wider">Question {currentQuestion + 1} of 30</span>
            <button 
              onClick={toggleReview}
              className={`flex items-center gap-2 text-sm font-medium transition-colors ${markedForReview.has(currentQuestion) ? 'text-yellow-600' : 'text-gray-400 hover:text-gray-600'}`}
            >
              <Flag className={`w-4 h-4 ${markedForReview.has(currentQuestion) ? 'fill-yellow-600' : ''}`} />
              {markedForReview.has(currentQuestion) ? 'Marked for Review' : 'Mark for Review'}
            </button>
          </div>

          <h2 className="text-xl md:text-2xl font-medium text-gray-800 mb-8 whitespace-pre-wrap font-mono leading-relaxed">
            {q.text}
          </h2>

          <div className="space-y-3 max-w-2xl">
            {q.opts.map((opt, idx) => (
              <label 
                key={idx} 
                className={`flex items-center p-4 rounded-lg border-2 cursor-pointer transition-all group ${
                  answers[currentQuestion] === idx 
                    ? 'border-blue-600 bg-blue-50' 
                    : 'border-gray-200 hover:border-gray-300 hover:bg-gray-50'
                }`}
              >
                <input 
                  type="radio" 
                  name={`q-${currentQuestion}`} 
                  className="w-5 h-5 text-blue-600 focus:ring-blue-500"
                  checked={answers[currentQuestion] === idx}
                  onChange={() => handleAnswer(idx)}
                />
                <span className={`ml-3 font-mono text-sm md:text-base ${answers[currentQuestion] === idx ? 'text-blue-900 font-medium' : 'text-gray-700'}`}>
                  {opt}
                </span>
              </label>
            ))}
          </div>
        </div>

        {/* Footer */}
        <div className="p-4 bg-gray-50 border-t flex justify-between items-center">
          <button 
            onClick={() => setCurrentQuestion(prev => Math.max(0, prev - 1))}
            disabled={currentQuestion === 0}
            className="px-6 py-2 rounded-lg border border-gray-300 text-gray-600 disabled:opacity-50 hover:bg-white transition"
          >
            ← Previous
          </button>
          
          {currentQuestion === 29 ? (
             <button 
               onClick={() => setExamStatus('review')}
               className="px-8 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 font-bold shadow-sm transition"
             >
               Finish & Review
             </button>
          ) : (
            <button 
              onClick={() => setCurrentQuestion(prev => Math.min(29, prev + 1))}
              className="px-8 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 font-bold shadow-sm transition"
            >
              Next Question →
            </button>
          )}
        </div>
      </div>
    </div>
  );
}